name: Secure POST Request Handler

on:
  workflow_dispatch: # Allows manual triggers
    inputs:
      secret_key:
        description: "Secret key to validate the request"
        required: true
  repository_dispatch: # Allows external POST requests
    types:
      - get-password

jobs:
  handle-post-request:
    runs-on: ubuntu-latest

    steps:
      - name: Validate the request
        run: |
          if [ "${{ github.event.client_payload.secret_key }}" != "YOUR_SECRET_KEY_HERE" ]; then
            echo "Invalid secret key!"
            exit 1
          fi
          echo "Valid request!"
      - name: Return the password
        run: |
          echo "Password: VREIUB8B473YW8NV"
